version: '3.9'

services:
  auth:
    build: ./auth_service
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/__health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s  

  weather:
    build: ./weather_service
    ports:
      - "8001:80"

  krakend_ce:
    image: devopsfaith/krakend:watch
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "8080:8080"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    depends_on:
      - auth
      - weather    

  db:
    image: postgres:14.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: klim
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
 
volumes:
  postgres_data:  